---
title: "Which British teams have been ranked number one in Europe?"
author: "John Knight"
draft: true
---

<!-- Liverpool 3481 days last 2025 -->
<!-- Man City 1127 days last 2024 -->
<!-- Man Utd 992 days last 2009 -->
<!-- Chelsea 664 days last 2009 -->
<!-- Leeds 575 days last 1974 -->
<!-- Celtic 533 days last 1972 -->
<!-- Everton 378 days last 1987 -->
<!-- Aberdeen 166 days last 1984 -->
<!-- Arsenal 149 days last 2026 -->
<!-- Hibernian 26 days last 1951 -->
<!-- Tottenham 18 days last 1985 -->
<!-- Nottm For 14 days last 1979 -->

As a football nerd, I love playing around on the [Club Elo](http://clubelo.com) website. One thing I noticed is that each club's page shows their highest rating, and when they most recently had that rating. So it got me wondering: which British teams have reached #1 in the Elo rankings?

We know which teams have been champions of Europe: Celtic, Manchester United, Liverpool, Nottingham Forest, Aston Villa, Chelsea and Manchester City. But that doesn't necessarily mean reaching #1; Villa, for example, only reached a ranking of 6th in the early 80s despite winning the English league title and the European Cup back-to-back. *Explain why...came out of nowhere and disappeared again...only 10th in the year they won EC...is that the lowest of any team?*

Introduce Club Elo as a fun and somewhat effective measure. Best in the world? Elo doesn't include South American teams which would have been an interesting debate until recently but not enough crossover.

Dominant eras by country. Start: Spain. How was this decided? 1940s: Spain, Italy (Torino: plane crash), Malmo!? 1950s: Austria, Italy, Scotland, Spain, Hungary. European Cup era (1955-1956 first season): Hungary then RM. Finally Inter in 1965. 1968 Scotland (Celtic) then the English era 1970s and 1980s. Ajax & Bayern early 1970s plus Feyenoord & Gladbach. Germany good in the 80s too! Then 90s, Italy.

*Show the percentage of days occupied by each country in each decade. Side-by-side bar chart?*

Start from #12 Forest...

12. Nottingham Forest

Promoted, League, European Cup, European Cup. Clough. Derby. Leeds. Peter Taylor. Meh, keep it short, has to be one paragraph tops really.

11. Tottenham

You would think 1960s but no! Some great 1980s sides but often undone by heavy schedule/injuries instead of peaking once.

10. Hibernian

Wait what?

9. Arsenal

Cunts.

8. Aberdeen

Fergie, wow. Broke the Auld Firm stranglehold. Joined in summer of 1978. 4-1-2-2-3-1-1-4. Won 4 Scottish Cups and the Cup Winners' Cup.

7. Everton

Quality in 60s and 80s

6. Celtic

Famous 1967 team but continued being great until 1972

5. Leeds

The great unheralded team of English football.

4. Chelsea

New money

3. Man Utd

Then and now.

2. Man City

New money

1. Liverpool

The best by MILES. Shanks.