<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="John Knight">
<meta name="dcterms.date" content="2026-08-01">
<meta name="description" content="Does Kalshi’s 7% fee per bet make many strategies unworkable?">

<title>How does Kalshi’s commission structure compare to Betfair? – John Knight Stats</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-b85bc7c33db8c58e0ec93c3465666fed.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-9d96f532d65220ca877c0304385df42f.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-df07115ad9f15e2ef3479c789e6873c8.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../../site_libs/bootstrap/bootstrap-9d96f532d65220ca877c0304385df42f.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed fullcontent quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">John Knight Stats</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../posts/index.html"> 
<span class="menu-text">Articles</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../projects/index.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../papers/index.html"> 
<span class="menu-text">Papers</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../tools/index.html"> 
<span class="menu-text">Tools</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../dashboards/index.html"> 
<span class="menu-text">Dashboards</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">How does Kalshi’s commission structure compare to Betfair?</h1>
  <div class="quarto-categories">
    <div class="quarto-category">betting</div>
    <div class="quarto-category">statistics</div>
    <div class="quarto-category">Kalshi</div>
    <div class="quarto-category">Betfair</div>
  </div>
  </div>

<div>
  <div class="description">
    Does Kalshi’s 7% fee per bet make many strategies unworkable?
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>John Knight </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">1 August 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="centered-block">
<p><img src="kalshi_on_phone.png"></p>
</div>
<p><br> It is hard to escape the current ubiquity of the prediction market platform <strong>Kalshi</strong> in the United States. Given my extensive background with the world’s leading betting exchange, <strong>Betfair</strong>, I was naturally curious how Kalshi’s exchange model compares.</p>
<p>Betfair’s arrival on the U.K. betting scene at the turn of the century was truly a game-changer for punters. Most obviously, the novel peer-to-peer format allowed better prices, trading in and out of positions, and more extensive in-running markets. But also, and perhaps more importantly, there actually existed the prospect that you could be a winning punter and not have your account promptly closed, as is the case with high street bookies like William Hill or Ladbrokes.</p>
<p>The American betting landscape is a lot more complicated than Britain’s, with piecemeal laws existing across various states due to moral objections, political lobbying and vested interests. In fact, Kalshi just got <a href="https://finance.yahoo.com/markets/options/articles/york-sues-kalshi-illegal-gambling-172947684.html">sued by the state of New York</a> for running an illegal gambling operation. I’m not getting into all that stuff because I’m ultimately a numbers man; what I am interested in is how does Kalshi compare to Betfair in terms of pricing, liquidity and bet-matching?</p>
<p>The first thing to note is that while Kalshi and Betfair are both betting exchanges, Kalshi frames its bets as <strong>contracts</strong>. I assume this is done to maintain the pretence that a prediction market is more like a financial market than sports betting, even when the contract is on whether or not a football team will win a match. Each contract pays out $1 if the bet wins, and the price of the contract is what is being agreed between the buyer and seller. Simple example: a 50¢ contract means the buyer pays 50 cents for the contract and doubles his money if it wins. So it is easiest to frame this in percentage terms: buying a 50¢ contract means you think the probability is greater than 50%, and selling the contract means you think it is lower than 50%.</p>
<p>Originally, Kalshi offered all markets in price increments of 1¢ (51¢, 52¢, 53¢, etc). At some point, they decided to offer certain larger markets, like the World Cup, in smaller increments (51.1¢, 51.2¢, 51.3¢, etc).</p>
<p>A quick glance at any major market on Kalshi shows that liquidity isn’t a problem and gross prices (i.e.&nbsp;before commission) are good. For example, I randomly opened a live baseball game between Philadelphia and Miami and saw that you can buy or sell Philly at 58¢ or 57¢ for large volume. This is equivalent to a spread of 1.724 - 1.754 in decimal prices, or a 101% book.</p>
<div class="centered-block">
<p><img src="philly_miami.jpg"></p>
</div>
<p><br> The question is of course, how much do you then have to pay in commission on winning bets? On Betfair, you would have to pay <strong>2%</strong> of your net profit per market. What about Kalshi? The answer is, it depends!</p>
<p>Kalshi uses different rates of commission — or <strong>fees</strong> as they call them — depending on whether you are a <strong>market-maker</strong> or a <strong>price-taker</strong> (I will henceforth refer to these as ‘maker’ and ‘taker’). Whenever a bet is matched between two parties on an exchange, naturally one party was in the market first with their order waiting to be matched (the maker), and the other party subsequently matched it (the taker).</p>
<p>The fees are calculated using the formulae</p>
<p><span class="math display">\[
F_{\text{taker}} = 0.07\cdot C\cdot P(1-P)
\]</span></p>
<p><span class="math display">\[
F_{\text{maker}} = 0.0175\cdot C \cdot P(1-P)
\]</span></p>
<p>where <span class="math inline">\(C\)</span> = number of contracts and <span class="math inline">\(P\)</span> = price in decimal form i.e.&nbsp;50¢ = 0.5.</p>
<p>The formulae for calculating the maker’s fee and the taker’s fee look complicated but they actually aren’t. On Kalshi you pay the fee when the bet is matched, so you are paying commission whether you win or lose. But the <span class="math inline">\(P(1-P)\)</span> part of the formula ensures that your fee reflects both the amount you stand to win and the probability of winning. Fees are smaller nearer to 0¢ and 100¢ than near 50¢, but that’s because a) you stand to win a lot less when buying near 100¢ and b) you win less often when buying near 0¢. The end result is that that your long-term commission will be equivalent to a rate of 1.75% for makers and 7% for takers.</p>
<p>To confirm this is correct, I calculated and compared the two methods using R software at three different price levels (see below). Note that this assumes each bet’s probability of winning is in line with the price. If you are a profitable bettor then your bets will win more often, meaning your fees paid will end up a bit lower than the equivalent Betfair commission rate, and vice versa for long-term losers.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-2-2.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-2-3.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>So how bad is 7% commission? If a market is a coin flip (e.g.&nbsp;an NFL or NBA handicap market) then buying at 50¢ on Kalshi would be buying at 51.75¢ after the taker fee. This is equivalent to 1.932 decimal or -107 in American odds. It’s not amazing value, but it’s good enough that a recreational punter will accept it for the convenience of a single app where they can bet on seemingly anything — especially if they live in a large state like California or Texas where there are no other legal options.</p>
<p>The proposition for makers is, of course, much more favourable, as the 1.75% commission makes the same bet equivalent to 1.983 decimal or -101.8 in American odds.</p>
<p>To illustrate the long-term effect of commission, the below chart shows the profit distribution after 1,000 bets for a punter who has an edge: he is consistently buying bets at 50¢ that have a 52% chance of winning. This may not sound like much of an edge but this would put you in elite territory in any high-liquidity market!</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 26%">
<col style="width: 20%">
<col style="width: 24%">
<col style="width: 28%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Fee structure</th>
<th style="text-align: right;">Expected profit</th>
<th style="text-align: right;">Standard deviation</th>
<th style="text-align: right;">Probability of profit</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">No fees</td>
<td style="text-align: right;">$4,000</td>
<td style="text-align: right;">$3,160</td>
<td style="text-align: right;">89.1%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Kalshi maker (1.75%)</td>
<td style="text-align: right;">$3,125</td>
<td style="text-align: right;">$3,160</td>
<td style="text-align: right;">83.7%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Betfair (2%)</td>
<td style="text-align: right;">$2,960</td>
<td style="text-align: right;">$3,128</td>
<td style="text-align: right;">82.1%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Kalshi taker (7%)</td>
<td style="text-align: right;">$500</td>
<td style="text-align: right;">$3,160</td>
<td style="text-align: right;">56.3%</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><br> In the fantasy scenario of zero fees, the expected profit after 1,000 bets is +$4,000 with an 89.1% probability of being in profit. At 1.75% the expected profit drops to +$3,125, and Betfair’s 2% commission eats up more than a quarter of your long-term profits as the expected +$4,000 drops to $2,960. But on Kalshi’s 7% fees your expected profit would be only +$500 with a 56.3% chance of being ahead and 43.7% probability of being down overall.</p>
<p>So this begs the question: why ever be a taker?</p>
<ol type="1">
<li><p><strong>Recreational punters</strong>. Some people just aren’t price sensitive, or they can’t be bothered to waste time shopping around for the best price. If I’m being honest, this is my approach to lots of things in life! It would be exhausting to try and secure the best price every time I pay for something, so I totally understand this behaviour.</p></li>
<li><p>You have a big edge thanks to some <strong>new information</strong>. If you found out about some major event (e.g.&nbsp;a goal or a big injury) more quickly than anyone else, then obviously you are happy to pay 7% fees if you know that the market is dramatically wrong and the price is likely to change imminently. Fill your boots!</p></li>
<li><p>You have a special rebate deal (more on that shortly).</p></li>
</ol>
<p>In the absence of the above, it seems like anyone with the goal of making a long-term profit on Kalshi is forced into being a market-maker. The disadvantage for makers is that you may not get matched, or you may only get matched because of some new piece of information (see 2. above). Because of these factors, <strong>queue position</strong> becomes very important: if you are at the back of a very long queue then it becomes less likely that you get matched in the normal course of events, whereas if a goal or major injury occurs then you are absolutely definitely getting matched straight away, and you won’t be happy about it.</p>
<p>There’s another major difference between Kalshi and Betfair’s commission that has a huge effect on strategy. Kalshi charges a fee on every single bet, whereas Betfair only charges commission on your <strong>net</strong> position when the market is settled. This makes trading or micro-trading strategies a lot more viable on Betfair than on Kalshi.</p>
<p>For example, suppose you buy 10,000 contracts at 50¢ and sell them back at 53¢. Congratulations, you just made $300! On Betfair you would pay 2% commission on this $300, so your net win is $294. On Kalshi you would pay fees on both the buy AND the sell, so for makers the net win would be $300 - $43.75 - $43.59 = $212.66 while for takers it would be $300 - $175 - $174.37 = a net LOSS of $49.37!</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Commission structure</th>
<th style="text-align: right;">Gross profit</th>
<th style="text-align: right;">Fees</th>
<th style="text-align: right;">Net profit</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">No fees</td>
<td style="text-align: right;">$300.00</td>
<td style="text-align: right;">$0.00</td>
<td style="text-align: right;">$300.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">Betfair (2%)</td>
<td style="text-align: right;">$300.00</td>
<td style="text-align: right;">$6.00</td>
<td style="text-align: right;">$294.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Kalshi maker (1.75%)</td>
<td style="text-align: right;">$300.00</td>
<td style="text-align: right;">$87.34</td>
<td style="text-align: right;">$212.66</td>
</tr>
<tr class="even">
<td style="text-align: left;">Kalshi taker (7%)</td>
<td style="text-align: right;">$300.00</td>
<td style="text-align: right;">$349.37</td>
<td style="text-align: right;">-$49.37</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><br> Although on the face of it Betfair are leaving a lot of money on the table by only charging commission on net winnings, it does have a couple of advantages. Firstly, a trading strategy allows you to place much larger stakes as there is less of your bank at risk, assuming you can trade out if the price goes against you (this is a BIG assumption). And secondly, when you execute your second trade there is another party to that bet, so you are recycling money back into the market. It’s like the multiplier effect in economics. So maybe this approach is good for the ecosystem? I don’t have the answer to that, but I suspect it’s something that will vary depending on the liquidity and volatility of each particular market.</p>
<p>Finally, let’s address the elephant in the room. There are big players operating in the market with a huge advantage: <strong>rebate deals</strong>. In exchange for adding large volume, some organizations sign Market Maker deals which effectively give them much lower fees per bet than the average punter. This obviously puts them in a strong position as they may be able to execute ‘taker’ trades without the prohibitive costs. I won’t pretend to know all the inner workings of these deals, and I should also point out that Kalshi has other <a href="https://help.kalshi.com/en/collections/18616618-programs-promotions">incentive programs</a> to encourage liquidity.</p>
<p>Originally this was just some private research as I was considering whether Kalshi is worth my time &amp; effort to see if it could be a viable income source. I realised this might be of interest to others, so I turned it into this article. So, is Kalshi worth it? I’m going to say yes overall, simply because of the amount of money sloshing around from price-insensitive, inexperienced Americans. And there’s never any harm in keeping your tools sharp of course; I’ve been out of the game for a few years but it’s always good to be ready for the next opportunity.</p>
<p>What about the Kalshi ecosystem? Is that amenable to long-term health? That’s not my area of expertise, but I’m sure Kalshi recruited people with industry experience and came up with this very deliberate two-tiered fee system. There’s obviously a first-mover advantage with these things and everyone is familiar with Kalshi now, so it feels like they will have to either mess it up or get banned by the government, otherwise the ceiling is very high. I’ve only had a few bets so far — fortunately (aftertiming alert) one of those was on Spain to win the World Cup — but I’m going to continue having a play around with it and see what happens. Small stakes to begin with, of course. Please bet responsibly! And if anyone with more experience of Kalshi has anything to add, I would love to hear it.</p>
<div class="data-footer">
<p><strong>Data Sources</strong><br>
I gather match data from a variety of public sources. Please check out these excellent websites:</p>
<ul>
<li><a href="https://clubelo.com">Club Elo Ratings</a></li>
<li><a href="https://www.espn.com/soccer/">ESPN</a></li>
<li><a href="https://fbref.com">FBref</a></li>
<li><a href="https://fotmob.com">FotMob</a></li>
<li><a href="https://transfermarkt.com">Transfermarkt</a></li>
<li><a href="https://understat.com">Understat</a></li>
<li><a href="https://whoscored.com">WhoScored</a></li>
<li><a href="http://eloratings.net/">World Football Elo Ratings</a></li>
</ul>
<p>I welcome feedback! Feel free to contact me at <a href="mailto:knightjohn2@gmail.com">knightjohn2@gmail.com</a>.</p>
</div>
<p>© 2026 John Knight. All rights reserved.</p>



</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/johnknightstats\.com");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>